SELECT R.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES 
    FROM REST_INFO 
    GROUP BY FOOD_TYPE
) T
ON R.FOOD_TYPE = T.FOOD_TYPE AND R.FAVORITES = T.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC