WITH RECURSIVE HOURS (HOUR) AS (
  SELECT 0
  UNION ALL
  SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)
SELECT H.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOURS H
LEFT OUTER JOIN ANIMAL_OUTS A
ON HOUR(DATETIME) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR ASC